import sys
from PySide6.QtGui import QPixmap
from PySide6.QtCore import QSize, Qt, Signal
from PySide6.QtWidgets import QApplication, QListWidgetItem, QAbstractItemView
from fetch_thread import FetchThread
from frameless_window import WindowsFramelessWindow
from downloader_parse_base_ui import Ui_MainWindow
import core


class ParseResultWindow(WindowsFramelessWindow):
    addTaskSignal = Signal(dict)
    closedSignal = Signal(int)

    def __init__(self, parse_result) -> None:
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.setStyleSheet(core.QSS)

        self.ep_list = parse_result['ep_list']
        self.tokuten = parse_result['tokuten']
        self.manga_info = parse_result
        parse_result['ep_list'].reverse()
        parse_result['tokuten'].reverse()
        parse_result.pop('ep_list')
        parse_result.pop('tokuten')

        self.setWindowTitle('漫画详情')
        self.ui.LTitle.setText('解析结果')
        self.setWindowIcon(core.RESOURCE["logo_icon"])
        self.ui.LIcon.setPixmap(core.RESOURCE["logo_pixmap"])
        self.ui.PbMinimize.setIcon(core.RESOURCE["minimize_icon"])
        self.ui.PbClose.setIcon(core.RESOURCE["close_icon"])
        self.ui.PbMinimize.clicked.connect(self.window().showMinimized)
        self.ui.PbClose.clicked.connect(self.close)
        self.ui.PbMaximizeRestore.setIcon(core.RESOURCE["maximize_icon"])
        self.ui.PbMaximizeRestore.clicked.connect(self.toggleMaxState)

        self.ui.LMangaTitle.setText(self.manga_info['title'])
        self.ui.LAuthor.setText(", ".join(str(i)
                                for i in self.manga_info['author_name']))
        self.ui.LDescription.setText(self.manga_info['classic_lines'] + '\n')

        self.fetch_thread = FetchThread(self.manga_info['vertical_cover'])
        self.fetch_thread.resoponse_signal.connect(self.loadImage)
        self.fetch_thread.start()
        self.ui.PbDownload.setText('开始下载')
        self.ui.LChapterTitle.setText('章节列表')
        self.ui.PbCancelAll.setText('取消全部')
        self.ui.PbSelectAll.setText('选择全部')

        self.ui.PbSelectAll.clicked.connect(self.selectAll)
        self.ui.PbCancelAll.clicked.connect(self.cancelAll)
        self.ui.PbDownload.clicked.connect(self.addToDownloadList)

        self.ui.LwChapterList.setSelectionMode(
            QAbstractItemView.MultiSelection)

        for i in range(len(self.ep_list)):
            item = QListWidgetItem()
            item.setText('{}  {}'.format(
                self.ep_list[i]['short_title'], self.ep_list[i]['title']))

            if self.ep_list[i]['is_locked']:
                item.setFlags(item.flags() & Qt.NoItemFlags)
                item.setText("{} - 漫币：{}".format(item.text(),
                             self.ep_list[i]['pay_gold']))
            item.setSizeHint(QSize(0, 50))
            self.ui.LwChapterList.addItem(item)

        for i in range(len(self.tokuten)):
            item = QListWidgetItem()
            item.setText('{}  {}'.format(
                self.tokuten[i]['item']['title'], self.tokuten[i]['item']['detail']))

            if self.tokuten[i]['isLock']:
                item.setFlags(item.flags() & Qt.NoItemFlags)
            item.setSizeHint(QSize(0, 50))
            self.ui.LwChapterList.addItem(item)

    def loadImage(self, content):
        Cover = QPixmap()
        Cover.loadFromData(content)
        self.ui.LCover.setPixmap(Cover)

    def selectAll(self):
        """ select all items """
        for i in range(self.ui.LwChapterList.count()):
            item = self.ui.LwChapterList.item(i)
            if item.flags != Qt.NoItemFlags:
                item.setSelected(True)
            else:
                item.setSelected(False)

    def cancelAll(self):
        """ cancel all items """
        for i in range(self.ui.LwChapterList.count()):
            item = self.ui.LwChapterList.item(i)
            item.setSelected(False)

    def addToDownloadList(self):
        downloaditems = self.manga_info
        downloaditems['list'] = []
        downloaditems['tokuten'] = []
        for i in range(len(self.ep_list)):
            item = self.ui.LwChapterList.item(i)
            if item.isSelected():
                downloaditems['list'].append(self.ep_list[i])
        for i in range(len(self.tokuten)):
            item = self.ui.LwChapterList.item(len(self.ep_list) + i)
            if item.isSelected():
                downloaditems['tokuten'].append(self.tokuten[i])
        if len(downloaditems['list']) == 0 and len(downloaditems['tokuten']) == 0:
            print('no items')
            return
        self.addTaskSignal.emit(downloaditems)
        self.close()

    def applyTaskInList(self, tasks):
        if tasks == {}:
            return
        for i in range(len(self.ep_list)):
            item = self.ui.LwChapterList.item(i)
            if self.ep_list[i]['id'] in tasks:
                item.setSelected(True)
                item.setFlags(item.flags() & Qt.NoItemFlags)
                item.setText(
                    '{} {} - {}'.format(self.ep_list[i]['short_title'], self.ep_list[i]['title'], '已添加到任务列表中'))

        for i in range(len(self.tokuten)):
            item = self.ui.LwChapterList.item(len(self.ep_list) + i)
            if self.tokuten[i]['item']['id'] in tasks:
                item.setSelected(True)
                item.setFlags(item.flags() & Qt.NoItemFlags)
                item.setText(
                    '{} {} - {}'.format(self.tokuten[i]['item']['title'], self.tokuten[i]['item']['detail'], '已添加到任务列表中'))

    def changeIconMaximized(self):
        """ overload function """
        self.ui.PbMaximizeRestore.setIcon(core.RESOURCE["maximize_icon"])

    def changeIconNormalized(self):
        """ overload function """
        self.ui.PbMaximizeRestore.setIcon(core.RESOURCE["restore_icon"])

    def closeEvent(self, event) -> None:
        # check if thread is running
        if self.fetch_thread.isRunning():
            self.fetch_thread.terminate()
        self.closedSignal.emit(self.manga_info['id'])
        event.accept()


if __name__ == '__main__':
    """
    create and show window
    """
    app = QApplication(sys.argv)

    parse_result = {"id": 28903, "title": "迦希大人不气馁！", "horizontal_cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                    "classic_lines": "【此漫画的翻译由版权方提供】身为魔界No.2的迦希大人是受魔界万人景仰的存在···那是曾经。（原）魔界No.2的迦希大人······现在在人间操劳家务，忙碌于打工！！即使晚餐只有豆芽，在咖啡店里只能以水代咖啡，但也绝对不可能气馁！手帕是必不可少的泪目作！残念而又可爱的魔界复兴喜剧☆",
                    "author_name": ["昆布わかめ", "SE社"],
                    "vertical_cover": "https://i0.hdslb.com/bfs/manga-static/0fda3912c206c98c622c7ee84a7b916ecc7ea59c.jpg",
                    "ep_list": [
                        {
                            "id": 757677,
                            "ord": 82,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": True,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "73",
                            "is_in_free": False,
                            "title": "迦希大人与真相",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2022-04-22 22:28:18",
                            "comments": 58,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 111,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 728406,
                            "ord": 81,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "72",
                            "is_in_free": False,
                            "title": "迦希大人与努力",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2022-03-24 14:11:06",
                            "comments": 36,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 147,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 700791,
                            "ord": 80,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 17925024,
                            "short_title": "71",
                            "is_in_free": False,
                            "title": "迦希大人与演出",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2022-02-22 20:36:14",
                            "comments": 55,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 162,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 689650,
                            "ord": 79,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 10292352,
                            "short_title": "70",
                            "is_in_free": False,
                            "title": "迦希大人和游戏",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2022-01-21 16:39:23",
                            "comments": 37,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 165,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 672591,
                            "ord": 78,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 16543469,
                            "short_title": "69",
                            "is_in_free": False,
                            "title": "迦希大人与吃醋",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-12-22 19:00:11",
                            "comments": 56,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 164,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 662163,
                            "ord": 77,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 14521276,
                            "short_title": "68",
                            "is_in_free": False,
                            "title": "迦希大人与欢送会",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-11-22 17:48:40",
                            "comments": 60,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 165,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 652630,
                            "ord": 76,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "67",
                            "is_in_free": False,
                            "title": "迦希大人与大战的结果",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-10-22 12:00:00",
                            "comments": 67,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 189,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 641462,
                            "ord": 75,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 17656087,
                            "short_title": "66",
                            "is_in_free": False,
                            "title": "迦希大人与大战",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-09-22 18:56:14",
                            "comments": 76,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 188,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 624270,
                            "ord": 74,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 14222513,
                            "short_title": "65",
                            "is_in_free": False,
                            "title": "迦希大人和幕后黑手的出现",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-08-20 18:37:50",
                            "comments": 80,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 207,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 600037,
                            "ord": 73,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 16298953,
                            "short_title": "64",
                            "is_in_free": False,
                            "title": "迦希大人和独立",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-07-21 12:00:00",
                            "comments": 41,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 182,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 591473,
                            "ord": 72,
                            "read": 1,
                            "pay_mode": 0,
                            "is_locked": False,
                            "pay_gold": 0,
                            "size": 3977404,
                            "short_title": "62.5",
                            "is_in_free": False,
                            "title": "迦希大人与抬完神轿之后",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-06-22 12:00:00",
                            "comments": 61,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 0,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 205,
                            "chapter_id": 0,
                            "type": 2,
                            "extra": 0
                        },
                        {
                            "id": 581910,
                            "ord": 71,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 18114596,
                            "short_title": "63",
                            "is_in_free": False,
                            "title": "萨鲁瓦大人和庙会",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-05-21 12:00:00",
                            "comments": 75,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 173,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 573207,
                            "ord": 70,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 16188906,
                            "short_title": "62",
                            "is_in_free": False,
                            "title": "迦希大人与抬神轿",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-04-22 12:00:00",
                            "comments": 40,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 172,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 563425,
                            "ord": 69,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 18119861,
                            "short_title": "61",
                            "is_in_free": False,
                            "title": "德鲁洁与迦希大人",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-03-22 12:00:00",
                            "comments": 72,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 170,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 553970,
                            "ord": 68,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 14379252,
                            "short_title": "60",
                            "is_in_free": False,
                            "title": "迦希大人与迷之光",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-02-22 14:34:07",
                            "comments": 27,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 171,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 543787,
                            "ord": 67,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "59",
                            "is_in_free": False,
                            "title": "迦希大人与鬼",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2021-01-22 12:00:00",
                            "comments": 35,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 150,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 528156,
                            "ord": 66,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 9161826,
                            "short_title": "58",
                            "is_in_free": False,
                            "title": "魔王大人与魔法少女",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-12-22 12:00:00",
                            "comments": 30,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 160,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 516685,
                            "ord": 65,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 9986096,
                            "short_title": "57",
                            "is_in_free": False,
                            "title": "和迦希大人一起住",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-20 16:07:25",
                            "comments": 39,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 169,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 507096,
                            "ord": 64,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 8063938,
                            "short_title": "56",
                            "is_in_free": False,
                            "title": "魔王大人的一天",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 45,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 140,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 507095,
                            "ord": 63,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 8967446,
                            "short_title": "55",
                            "is_in_free": False,
                            "title": "迦希大人与好朋友",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 33,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 153,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 507092,
                            "ord": 62,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 15408099,
                            "short_title": "54",
                            "is_in_free": False,
                            "title": "迦希大人与宿命的对决",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 41,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 146,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 507091,
                            "ord": 61,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 14938325,
                            "short_title": "53",
                            "is_in_free": False,
                            "title": "萨鲁瓦与宿命的一战",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 17,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 133,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506763,
                            "ord": 60,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 15242560,
                            "short_title": "52",
                            "is_in_free": False,
                            "title": "德鲁洁，回想起来了",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 13,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 140,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506762,
                            "ord": 59,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13612219,
                            "short_title": "51",
                            "is_in_free": False,
                            "title": "迦希大人与生活品质",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 16,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 138,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506761,
                            "ord": 58,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 12763989,
                            "short_title": "50",
                            "is_in_free": False,
                            "title": "萨鲁瓦与志愿者",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 24,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 128,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506760,
                            "ord": 57,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 12447619,
                            "short_title": "49",
                            "is_in_free": False,
                            "title": "迦希大人与开发新菜单",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 21,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 134,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506759,
                            "ord": 56,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 14190350,
                            "short_title": "48",
                            "is_in_free": False,
                            "title": "迦希大人与魔王大人的过去",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 22,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 147,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506758,
                            "ord": 55,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 14215005,
                            "short_title": "47",
                            "is_in_free": False,
                            "title": "萨鲁瓦与魔法少女",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 22,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 131,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506757,
                            "ord": 54,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 14323367,
                            "short_title": "46",
                            "is_in_free": False,
                            "title": "德鲁洁与魔法少女",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 22,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 138,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506752,
                            "ord": 53,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 12289054,
                            "short_title": "45",
                            "is_in_free": False,
                            "title": "迦希大人与打工的后辈",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 32,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 141,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506734,
                            "ord": 52,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13880994,
                            "short_title": "44",
                            "is_in_free": False,
                            "title": "迦希大人与大家一起玩",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 19,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 130,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506733,
                            "ord": 51,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13930848,
                            "short_title": "43",
                            "is_in_free": False,
                            "title": "迦希大人与信赖",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 27,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 137,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506732,
                            "ord": 50,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 21062147,
                            "short_title": "42",
                            "is_in_free": False,
                            "title": "迦希大人与魔王大人",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 29,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 155,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506728,
                            "ord": 49,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 2724552,
                            "short_title": "特别篇",
                            "is_in_free": False,
                            "title": "德鲁洁的思绪 附赠",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 17,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 113,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506726,
                            "ord": 48,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "41",
                            "is_in_free": False,
                            "title": "迦希大人与魔法少女的家",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 29,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 143,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506723,
                            "ord": 47,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 23362391,
                            "short_title": "40",
                            "is_in_free": False,
                            "title": "迦希大人与决战的时刻",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 81,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 156,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506720,
                            "ord": 46,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 16298895,
                            "short_title": "39",
                            "is_in_free": False,
                            "title": "迦希大人与德鲁洁的思绪",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 23,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 152,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506716,
                            "ord": 45,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 16499401,
                            "short_title": "38",
                            "is_in_free": False,
                            "title": "迦希大人与寄存魔石",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 29,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 142,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506714,
                            "ord": 44,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 22551805,
                            "short_title": "37",
                            "is_in_free": False,
                            "title": "迦希大人与海滨小屋",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 20,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 138,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506711,
                            "ord": 43,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 17602530,
                            "short_title": "36",
                            "is_in_free": False,
                            "title": "迦希大人与发现了魔石",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 12,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 155,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506695,
                            "ord": 42,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13894263,
                            "short_title": "35",
                            "is_in_free": False,
                            "title": "迦希大人与公园探索",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 14,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 147,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506694,
                            "ord": 41,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13276316,
                            "short_title": "34",
                            "is_in_free": False,
                            "title": "迦希大人与汪汪汪",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 25,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 158,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506682,
                            "ord": 40,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "33",
                            "is_in_free": False,
                            "title": "迦希大人与西红柿",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 19,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 151,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506681,
                            "ord": 39,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 5444827,
                            "short_title": "特别篇",
                            "is_in_free": False,
                            "title": "迦希大人与姐妹的过去",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 11,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 142,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506680,
                            "ord": 38,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "32",
                            "is_in_free": False,
                            "title": "迦希大人与离家出走的房东",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 50,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 164,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506677,
                            "ord": 37,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "31",
                            "is_in_free": False,
                            "title": "迦希大人与打工达人",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 28,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 162,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506676,
                            "ord": 36,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 15011367,
                            "short_title": "30",
                            "is_in_free": False,
                            "title": "迦希大人与进度报告会",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 28,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 169,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506674,
                            "ord": 35,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 14260407,
                            "short_title": "29",
                            "is_in_free": False,
                            "title": "迦希大人与对抗心",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 18,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 171,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506673,
                            "ord": 34,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 15112951,
                            "short_title": "28",
                            "is_in_free": False,
                            "title": "迦希大人与魔法少女的愿望",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 25,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 169,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506670,
                            "ord": 33,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 15723602,
                            "short_title": "27",
                            "is_in_free": False,
                            "title": "萨鲁瓦大人也去澡堂",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 37,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 182,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506669,
                            "ord": 32,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "26",
                            "is_in_free": False,
                            "title": "迦希大人去澡堂",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 59,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 181,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506666,
                            "ord": 31,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13112201,
                            "short_title": "25",
                            "is_in_free": False,
                            "title": "迦希大人与手工陷阱",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 40,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 172,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506654,
                            "ord": 30,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 20081160,
                            "short_title": "24",
                            "is_in_free": False,
                            "title": "迦希大人与购物中心",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 18,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 168,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506639,
                            "ord": 29,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 3322225,
                            "short_title": "特别篇",
                            "is_in_free": False,
                            "title": "迦希大人与猫咪咖啡馆",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 20,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 141,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506637,
                            "ord": 28,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 17433488,
                            "short_title": "23",
                            "is_in_free": False,
                            "title": "迦希大人与魔界聚会",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 30,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 175,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506632,
                            "ord": 27,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 15173390,
                            "short_title": "22",
                            "is_in_free": False,
                            "title": "迦希大人与邻里纠纷",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 24,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 181,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506631,
                            "ord": 26,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13524420,
                            "short_title": "21",
                            "is_in_free": False,
                            "title": "迦希大人与肌肉锻炼",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 19,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 180,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506630,
                            "ord": 25,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 12761532,
                            "short_title": "20",
                            "is_in_free": False,
                            "title": "迦希大人与魔界精英的烦恼",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 23,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 192,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506629,
                            "ord": 24,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 15315474,
                            "short_title": "19",
                            "is_in_free": False,
                            "title": "迦希大人与幸福的证明",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 22,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 206,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506627,
                            "ord": 23,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "18",
                            "is_in_free": False,
                            "title": "迦希大人与酒",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 21,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 192,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506626,
                            "ord": 22,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "17",
                            "is_in_free": False,
                            "title": "迦希大人与危险少女",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 42,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 189,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506624,
                            "ord": 21,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "16",
                            "is_in_free": False,
                            "title": "迦希大人与恐惧心理",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 33,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 223,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506622,
                            "ord": 20,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "15",
                            "is_in_free": False,
                            "title": "迦希大人与魔法少女",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 38,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 220,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506617,
                            "ord": 19,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "特别篇",
                            "is_in_free": False,
                            "title": "迦希大人与房租",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 30,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 184,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506607,
                            "ord": 18,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "14",
                            "is_in_free": False,
                            "title": "迦希大人与感冒",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 43,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 220,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506604,
                            "ord": 17,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "13",
                            "is_in_free": False,
                            "title": "迦希大人与演讲会",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 26,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 211,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506602,
                            "ord": 16,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 0,
                            "short_title": "12",
                            "is_in_free": False,
                            "title": "迦希大人与警察的盘问",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 29,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 218,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506599,
                            "ord": 15,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 18337181,
                            "short_title": "11",
                            "is_in_free": False,
                            "title": "迦希大人与萨鲁瓦再度登场",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 30,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 242,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506597,
                            "ord": 14,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13451099,
                            "short_title": "10",
                            "is_in_free": False,
                            "title": "迦希大人与生活费",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 41,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 225,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506595,
                            "ord": 13,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13976697,
                            "short_title": "9",
                            "is_in_free": False,
                            "title": "迦希大人与刺客",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 59,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 258,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506594,
                            "ord": 12,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13762372,
                            "short_title": "8",
                            "is_in_free": False,
                            "title": "迦希大人与德鲁洁与店长",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 42,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 274,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506589,
                            "ord": 11,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 13960190,
                            "short_title": "7",
                            "is_in_free": False,
                            "title": "迦希大人想要炫耀",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 40,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 314,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506588,
                            "ord": 10,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 17090132,
                            "short_title": "6",
                            "is_in_free": False,
                            "title": "迦希大人与魔石之力",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 38,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 321,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506586,
                            "ord": 9,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 6735125,
                            "short_title": "特别篇",
                            "is_in_free": False,
                            "title": "迦希大人华丽的一天",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 24,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 190,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506585,
                            "ord": 8,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 18310614,
                            "short_title": "5",
                            "is_in_free": False,
                            "title": "迦希大人与山",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 44,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 364,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506583,
                            "ord": 7,
                            "read": 1,
                            "pay_mode": 1,
                            "is_locked": False,
                            "pay_gold": 49,
                            "size": 12394295,
                            "short_title": "4",
                            "is_in_free": False,
                            "title": "迦希大人与房东",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 75,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 1,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 414,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506582,
                            "ord": 6,
                            "read": 1,
                            "pay_mode": 0,
                            "is_locked": False,
                            "pay_gold": 0,
                            "size": 12344852,
                            "short_title": "3",
                            "is_in_free": False,
                            "title": "迦希大人与重要的魔石",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 80,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 0,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 958,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506581,
                            "ord": 5,
                            "read": 1,
                            "pay_mode": 0,
                            "is_locked": False,
                            "pay_gold": 0,
                            "size": 16475446,
                            "short_title": "2",
                            "is_in_free": False,
                            "title": "迦希大人与高级公寓",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 59,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 0,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 1007,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506579,
                            "ord": 4,
                            "read": 1,
                            "pay_mode": 0,
                            "is_locked": False,
                            "pay_gold": 0,
                            "size": 18456405,
                            "short_title": "1",
                            "is_in_free": False,
                            "title": "迦希大人与打工",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 68,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 0,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 1084,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506578,
                            "ord": 3,
                            "read": 1,
                            "pay_mode": 0,
                            "is_locked": False,
                            "pay_gold": 0,
                            "size": 14819000,
                            "short_title": "0.3",
                            "is_in_free": False,
                            "title": "迦希大人与小学生",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 49,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 0,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 1109,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506577,
                            "ord": 2,
                            "read": 1,
                            "pay_mode": 0,
                            "is_locked": False,
                            "pay_gold": 0,
                            "size": 16366060,
                            "short_title": "0.2",
                            "is_in_free": False,
                            "title": "迦希大人与部下",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 79,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 0,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 1308,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        },
                        {
                            "id": 506575,
                            "ord": 1,
                            "read": 1,
                            "pay_mode": 0,
                            "is_locked": False,
                            "pay_gold": 0,
                            "size": 20921622,
                            "short_title": "0.1",
                            "is_in_free": False,
                            "title": "迦希大人与微笑",
                            "cover": "https://i0.hdslb.com/bfs/manga-static/f4f52964e05815deb6069f24dee5c3eec7bdd6eb.jpg",
                            "pub_time": "2020-11-14 00:00:00",
                            "comments": 292,
                            "unlock_expire_at": "0000-00-00 00:00:00",
                            "unlock_type": 0,
                            "allow_wait_free": False,
                            "progress": "",
                            "like_count": 1780,
                            "chapter_id": 0,
                            "type": 0,
                            "extra": 0
                        }
                    ]}

    widget = ParseResultWindow(parse_result)
    widget.show()

    sys.exit(app.exec())
